src/Entity/Campaign.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CampaignRepository")
 */
class Campaign
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_campaign;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    private $object_campaign;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Template", inversedBy="FK_id_campaign")
     */
    private $FK_id_template;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Liste", inversedBy="FK_id_campaign")
     */
    private $FK_id_liste;

    public function __construct()
    {
        $this->FK_id_template = new ArrayCollection();
        $this->FK_id_liste = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameCampaign(): ?string
    {
        return $this->name_campaign;
    }

    public function setNameCampaign(string $name_campaign): self
    {
        $this->name_campaign = $name_campaign;

        return $this;
    }

    public function getObjectCampaign(): ?string
    {
        return $this->object_campaign;
    }

    public function setObjectCampaign(?string $object_campaign): self
    {
        $this->object_campaign = $object_campaign;

        return $this;
    }

    /**
     * @return Collection|template[]
     */
    public function getFKIdTemplate(): Collection
    {
        return $this->FK_id_template;
    }

    public function addFKIdTemplate(template $fKIdTemplate): self
    {
        if (!$this->FK_id_template->contains($fKIdTemplate)) {
            $this->FK_id_template[] = $fKIdTemplate;
        }

        return $this;
    }

    public function removeFKIdTemplate(template $fKIdTemplate): self
    {
        if ($this->FK_id_template->contains($fKIdTemplate)) {
            $this->FK_id_template->removeElement($fKIdTemplate);
        }

        return $this;
    }

    /**
     * @return Collection|liste[]
     */
    public function getFKIdListe(): Collection
    {
        return $this->FK_id_liste;
    }

    public function addFKIdListe(liste $fKIdListe): self
    {
        if (!$this->FK_id_liste->contains($fKIdListe)) {
            $this->FK_id_liste[] = $fKIdListe;
        }

        return $this;
    }

    public function removeFKIdListe(liste $fKIdListe): self
    {
        if ($this->FK_id_liste->contains($fKIdListe)) {
            $this->FK_id_liste->removeElement($fKIdListe);
        }

        return $this;
    }
}

src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $lastname_contact;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $firstname_contact;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $mail_contact;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Liste", mappedBy="FK_id_contact")
     */
    private $FK_id_liste;

    public function __construct()
    {
        $this->FK_id_liste = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName()
    {
        return $this->lastname_contact.' '.$this->firstname_contact;
    }

    public function getLastnameContact(): ?string
    {
        return $this->lastname_contact;
    }

    public function setLastnameContact(string $lastname_contact): self
    {
        $this->lastname_contact = $lastname_contact;

        return $this;
    }

    public function getFirstnameContact(): ?string
    {
        return $this->firstname_contact;
    }

    public function setFirstnameContact(string $firstname_contact): self
    {
        $this->firstname_contact = $firstname_contact;

        return $this;
    }

    public function getMailContact(): ?string
    {
        return $this->mail_contact;
    }

    public function setMailContact(string $mail_contact): self
    {
        $this->mail_contact = $mail_contact;

        return $this;
    }

    /**
     * @return Collection|Liste[]
     */
    public function getFKIdListe(): Collection
    {
        return $this->FK_id_liste;
    }

    public function addFKIdListe(Liste $fKIdListe): self
    {
        if (!$this->FK_id_liste->contains($fKIdListe)) {
            $this->FK_id_liste[] = $fKIdListe;
            $fKIdListe->addFKIdContact($this);
        }

        return $this;
    }

    public function removeFKIdListe(Liste $fKIdListe): self
    {
        if ($this->FK_id_liste->contains($fKIdListe)) {
            $this->FK_id_liste->removeElement($fKIdListe);
            $fKIdListe->removeFKIdContact($this);
        }

        return $this;
    }
}

src/Entity/Liste.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ListeRepository")
 */
class Liste
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $name_liste;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Contact", inversedBy="FK_id_liste")
     */
    private $FK_id_contact;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Campaign", mappedBy="FK_id_liste")
     */
    private $FK_id_campaign;

    public function __construct()
    {
        $this->FK_id_contact = new ArrayCollection();
        $this->FK_id_campaign = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameListe(): ?string
    {
        return $this->name_liste;
    }

    public function setNameListe(string $name_liste): self
    {
        $this->name_liste = $name_liste;

        return $this;
    }

    /**
     * @return Collection|contact[]
     */
    public function getFKIdContact(): Collection
    {
        return $this->FK_id_contact;
    }

    public function addFKIdContact(contact $fKIdContact): self
    {
        if (!$this->FK_id_contact->contains($fKIdContact)) {
            $this->FK_id_contact[] = $fKIdContact;
        }

        return $this;
    }

    public function removeFKIdContact(contact $fKIdContact): self
    {
        if ($this->FK_id_contact->contains($fKIdContact)) {
            $this->FK_id_contact->removeElement($fKIdContact);
        }

        return $this;
    }

    /**
     * @return Collection|Campaign[]
     */
    public function getFKIdCampaign(): Collection
    {
        return $this->FK_id_campaign;
    }

    public function addFKIdCampaign(Campaign $fKIdCampaign): self
    {
        if (!$this->FK_id_campaign->contains($fKIdCampaign)) {
            $this->FK_id_campaign[] = $fKIdCampaign;
            $fKIdCampaign->addFKIdListe($this);
        }

        return $this;
    }

    public function removeFKIdCampaign(Campaign $fKIdCampaign): self
    {
        if ($this->FK_id_campaign->contains($fKIdCampaign)) {
            $this->FK_id_campaign->removeElement($fKIdCampaign);
            $fKIdCampaign->removeFKIdListe($this);
        }

        return $this;
    }
}

src/Entity/Template.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TemplateRepository")
 */
class Template
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name_template;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $file_template;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Image")
     */
    private $FK_id_image;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Campaign", mappedBy="FK_id_template")
     */
    private $FK_id_campaign;

    public function __construct()
    {
        $this->FK_id_image = new ArrayCollection();
        $this->FK_id_campaign = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameTemplate(): ?string
    {
        return $this->name_template;
    }

    public function setNameTemplate(string $name_template): self
    {
        $this->name_template = $name_template;

        return $this;
    }

    public function getFileTemplate(): ?string
    {
        return $this->file_template;
    }

    public function setFileTemplate(?string $file_template): self
    {
        $this->file_template = $file_template;

        return $this;
    }

    /**
     * @return Collection|image[]
     */
    public function getFKIdImage(): Collection
    {
        return $this->FK_id_image;
    }

    public function addFKIdImage(image $fKIdImage): self
    {
        if (!$this->FK_id_image->contains($fKIdImage)) {
            $this->FK_id_image[] = $fKIdImage;
        }

        return $this;
    }

    public function removeFKIdImage(image $fKIdImage): self
    {
        if ($this->FK_id_image->contains($fKIdImage)) {
            $this->FK_id_image->removeElement($fKIdImage);
        }

        return $this;
    }

    /**
     * @return Collection|Campaign[]
     */
    public function getFKIdCampaign(): Collection
    {
        return $this->FK_id_campaign;
    }

    public function addFKIdCampaign(Campaign $fKIdCampaign): self
    {
        if (!$this->FK_id_campaign->contains($fKIdCampaign)) {
            $this->FK_id_campaign[] = $fKIdCampaign;
            $fKIdCampaign->addFKIdTemplate($this);
        }

        return $this;
    }

    public function removeFKIdCampaign(Campaign $fKIdCampaign): self
    {
        if ($this->FK_id_campaign->contains($fKIdCampaign)) {
            $this->FK_id_campaign->removeElement($fKIdCampaign);
            $fKIdCampaign->removeFKIdTemplate($this);
        }

        return $this;
    }
}

src/Form/CampaignType.php
<?php

namespace App\Form;

use App\Entity\Liste;
use App\Entity\Campaign;
use App\Entity\Template;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampaignType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_campaign', null, [
                'label' => "Nom de la campagne :",
            ])
            ->add('object_campaign', null, [
                'label' => "Objet de la campagne :",
            ])
            ->add('FK_id_template', EntityType::class, [
                'class' => Template::class,
                'choice_label' => 'name_template',
                'label' => "Ajouter un template :",
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('FK_id_liste', EntityType::class, [
                'class' => Liste::class,
                'choice_label' => 'name_liste',
                'label' => "Ajouter une ou plusieurs listes de contact :",
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Campaign::class,
        ]);
    }
}

src/Controller/CampaignController.php
<?php

namespace App\Controller;

use App\Entity\Campaign;
use App\Form\CampaignType;
use App\Repository\CampaignRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\JsonResponse;


/**
 * @Route("/campagne")
 */
class CampaignController extends AbstractController
{
    /**
     * @Route("/", name="campaign_index", methods={"GET"})
     */
    public function index(CampaignRepository $campaignRepository): Response
    {

        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];

        $serializer = new Serializer($normalizers, $encoders);

        $campaignData = $campaignRepository->findAll();

        $jsonObject = $serializer->serialize($campaignData, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        return $this->render('campaign/index.html.twig', [
            'campaigns' => $jsonObject,
            'current' => 'campagne',
        ]);
    }

    /**
     * @Route("/new", name="campaign_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $campaign = new Campaign();
        $form = $this->createForm(CampaignType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($campaign);
            $entityManager->flush();

            return $this->redirectToRoute('campaign_index');
        }

        return $this->render('campaign/new.html.twig', [
            'campaign' => $campaign,
            'form' => $form->createView(),
            'current' => 'campagne',
        ]);
    }

    /**
     * @Route("/{id}", name="campaign_show", methods={"GET"})
     */
    public function show(Campaign $campaign): Response
    {
        return $this->render('campaign/show.html.twig', [
            'campaign' => $campaign,
            'current' => 'campagne',
        ]);
    }

    /**
     * @Route("/{id}/mail", name="campaign_mail", methods={"GET"})
     */
    public function sendEmail(MailerInterface $mailer, Campaign $campaign)
    {
        $email = (new Email())
            ->from('hello@example.com')
            ->to('you@example.com')
            //->cc('cc@example.com')
            //->bcc('bcc@example.com')
            //->replyTo('fabien@example.com')
            //->priority(Email::PRIORITY_HIGH)
            ->subject('Time for Symfony Mailer!')
            ->text('Sending emails is fun again!')
            ->html('<p>See Twig integration for better HTML integration!</p>');

        $mailer->send($email);

        return $this->redirectToRoute('home');
    }

    /**
     * @Route("/{id}/edit", name="campaign_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Campaign $campaign): Response
    {
        $form = $this->createForm(CampaignType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('campaign_index');
        }

        return $this->render('campaign/edit.html.twig', [
            'campaign' => $campaign,
            'form' => $form->createView(),
            'current' => 'campagne',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="campaign_delete", methods={"POST"})
     */
    public function delete(Request $request, Campaign $campaign): Response
    {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($campaign);
            $entityManager->flush();

        return $this->redirectToRoute('campaign_index');
    }
}

templates/campaign/_delete_form.html.twig
<form method="post" class="pt-4" action="{{ path('campaign_delete', {'id': campaign.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campaign.id) }}">
    <button class="btn btn-danger ">Supprimer Campagne</button>
</form>

templates/campaign/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-6">
            {{ form_row(form.name_campaign) }}
        </div>
        <div class="col-6" >
            {{ form_row(form.object_campaign) }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {{ form_row(form.FK_id_template) }}
        </div>
        <div class="col-6" >
            {{ form_row(form.FK_id_liste) }}
        </div>
    </div>
    <div class="row justify-content-center pt-4">
        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/campaign/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition campagne{% endblock %}

{% block body %}
    
    <div class="row justify-content-between">
    <h1>Editer la Campagne</h1>
        <div>
            <a class="btn btn-secondary" href="{{ path('campaign_index') }}">Retour à la liste</a>
            {{ include('campaign/_delete_form.html.twig') }}
        </div>
    </div>

<div class="container pt-4">
    {{ include('campaign/_form.html.twig', {'button_label': 'Modifier'}) }}
</div>

{% endblock %}

templates/campaign/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des campagnes{% endblock %}

{% block body %}
    <div class="row justify-content-between">
        <h1>Liste des campagnes</h1>
        <div>
            <a class="btn btn-primary" href="{{ path('campaign_new') }}">
                Créer Campagne
            </a>
        </div>
        
    </div>

    
    <table-component 
    :datas="{{ campaigns }}"
    ></table-component>


    
{% endblock %}

templates/campaign/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Campaign{% endblock %}

{% block body %}

<div class="row justify-content-between">
    <h1>Créer une nouvelle campagne</h1>
    <div>
        <a class="btn btn-secondary" href="{{ path('campaign_index') }}">Retour à la liste</a>
    </div>
</div>

<div class="container pt-4">
    {{ include('campaign/_form.html.twig') }}
</div>
    

    
{% endblock %}

templates/campaign/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campagne{% endblock %}

{% block body %}
    <div class="row justify-content-between">
    <h1>Campagne</h1>
    <div>
        <a class="btn btn-secondary" href="{{ path('campaign_index') }}">Retour à la liste</a>
    </div>
</div>

    <table class="table pt-2">
        <tbody>
            <tr>
                <th>Nom de la Campagne</th>
                <td>{{ campaign.nameCampaign }}</td>
            </tr>
            <tr>
                <th>Objet de la Campagne</th>
                <td>{{ campaign.objectCampaign }}</td>
            </tr>
            <tr>
                <th>Template de la Campagne</th>
                <td>
                    {% for template in campaign.fkIdTemplate %}
                        <div class="card">
                            <div class="card-header">
                                {{ template.nameTemplate }}
                            </div>
                            <div class="card-body">
                                {{ template.fileTemplate|raw }}
                            </div>
                        </div> 
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Liste des Contact</th>
                <td>
                    {% for liste in campaign.fkIdListe %}
                        <div class="card">
                            <div class="card-header">
                                {{ liste.nameListe }}
                            </div>
                            <div class="card-body">
                                <ul>
                                    {% for contact in liste.fkIdContact %}
                                        <li>
                                        {{ contact.fullName }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div> 
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <form method="get" accept-charset="UTF-8" action="{{ path("campaign_mail", {'id': campaign.id})}}">
    
    <button class="btn btn-info">
        Lancer la Campagne
    </button>
    </form>

    <a href="{{ path('campaign_edit', {'id': campaign.id}) }}" class="btn mt-4 btn-primary">Modifier Campagne</a>

    {{ include('campaign/_delete_form.html.twig') }}
{% endblock %}