src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $lastname_contact;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $firstname_contact;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $mail_contact;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Liste", mappedBy="FK_id_contact")
     */
    private $FK_id_liste;

    public function __construct()
    {
        $this->FK_id_liste = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName()
    {
        return $this->lastname_contact.' '.$this->firstname_contact;
    }

    public function getLastnameContact(): ?string
    {
        return $this->lastname_contact;
    }

    public function setLastnameContact(string $lastname_contact): self
    {
        $this->lastname_contact = $lastname_contact;

        return $this;
    }

    public function getFirstnameContact(): ?string
    {
        return $this->firstname_contact;
    }

    public function setFirstnameContact(string $firstname_contact): self
    {
        $this->firstname_contact = $firstname_contact;

        return $this;
    }

    public function getMailContact(): ?string
    {
        return $this->mail_contact;
    }

    public function setMailContact(string $mail_contact): self
    {
        $this->mail_contact = $mail_contact;

        return $this;
    }

    /**
     * @return Collection|Liste[]
     */
    public function getFKIdListe(): Collection
    {
        return $this->FK_id_liste;
    }

    public function addFKIdListe(Liste $fKIdListe): self
    {
        if (!$this->FK_id_liste->contains($fKIdListe)) {
            $this->FK_id_liste[] = $fKIdListe;
            $fKIdListe->addFKIdContact($this);
        }

        return $this;
    }

    public function removeFKIdListe(Liste $fKIdListe): self
    {
        if ($this->FK_id_liste->contains($fKIdListe)) {
            $this->FK_id_liste->removeElement($fKIdListe);
            $fKIdListe->removeFKIdContact($this);
        }

        return $this;
    }
}

src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Liste;
use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname_contact', TextType::class)
            ->add('firstname_contact', TextType::class)
            ->add('mail_contact', TextType::class)
            ->add('FK_id_liste', EntityType::class, [
                // looks for choices from this entity
                'class' => Liste::class,

                // uses the User.username property as the visible option string
                'choice_label' => 'name_liste',
                
                'label' => "Ajouter à une ou plusieurs listes :",

                // used to render a select box, check boxes or radios
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * @Route("/contact")
 */
class ContactController extends AbstractController
{
    /**
     * @Route("/", name="contact_index", methods={"GET"})
     */
    public function index(ContactRepository $contactRepository): Response
    {
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];

        $serializer = new Serializer($normalizers, $encoders);

        $contactData = $contactRepository->findAll();

        $jsonObject = $serializer->serialize($contactData, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        return $this->render('contact/index.html.twig', [
            'contacts' => $jsonObject,
            'current' => 'Contact',
        ]);
    }

    /**
     * @Route("/new", name="contact_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contact);
            $entityManager->flush();

            return $this->redirectToRoute('contact_index');
        }

        return $this->render('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
            'current' => 'Contact',
        ]);
    }

    /**
     * @Route("/{id}", name="contact_show", methods={"GET"})
     */
    public function show(Contact $contact): Response
    {
        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
            'current' => 'Contact',
        ]);
    }

    /**
     * @Route("/{id}/edit", name="contact_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Contact $contact): Response
    {
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('contact_index');
        }

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
            'current' => 'Contact',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="contact_delete", methods={"POST"})
     */
    public function delete(Request $request, Contact $contact): Response
    {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($contact);
            $entityManager->flush();
        

        return $this->redirectToRoute('contact_index');
    }
}

templates/contact/_delete_form.html.twig
<form method="post" class="pt-4" action="{{ path('contact_delete', {'id': contact.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/contact/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-6">
            {{ form_row(form.lastname_contact) }}
        </div>
        <div class="col-6" >
            {{ form_row(form.firstname_contact) }}
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ form_row(form.mail_contact) }}
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ form_row(form.FK_id_liste) }}
        </div>
    </div>
    <div class="row justify-content-center pt-4">
        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contact{% endblock %}

{% block body %}
    <div class="row justify-content-between">
    <h1>Editer un Contact</h1>
        <div>
            <a class="btn btn-secondary" href="{{ path('contact_index') }}">Retour à la liste</a>
            {{ include('contact/_delete_form.html.twig') }}
        </div>
    </div>


<div class="container pt-4">
    {{ include('contact/_form.html.twig', {'button_label': 'Modifier'}) }}
</div>


    
{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact index{% endblock %}

{% block body %}
    <div class="row justify-content-between">
        <h1>Liste des contacts</h1>
        <div>
            <a class="btn btn-primary" href="{{ path('contact_new') }}">
                Créer Contact
            </a>
        </div>
        
    </div>

    
    <table-component 
    :datas="{{ contacts }}"
    ></table-component>

{% endblock %}

templates/contact/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Contact{% endblock %}

{% block body %}
    

    <div class="row justify-content-between">
        <h1>Creer un Contact</h1>
        <div>
            <a class="btn btn-secondary" href="{{ path('contact_index') }}">Retour à la liste</a>
        </div>
    </div>

<div class="container pt-4">
    {{ include('contact/_form.html.twig') }}
</div>

{% endblock %}

templates/contact/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
    <h1>Contact</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contact.id }}</td>
            </tr>
            <tr>
                <th>Lastname_contact</th>
                <td>{{ contact.lastnameContact }}</td>
            </tr>
            <tr>
                <th>Firstname_contact</th>
                <td>{{ contact.firstnameContact }}</td>
            </tr>
            <tr>
                <th>Mail_contact</th>
                <td>{{ contact.mailContact }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('contact_index') }}">back to list</a>

    <a href="{{ path('contact_edit', {'id': contact.id}) }}">edit</a>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}